config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :users
  resources :bookings

  resources :cameras, except: :index do
    # Define additional camera routes if needed
  end

  # Allow access to /cameras index route without authentication
  get '/cameras', to: 'cameras#index', constraints: { authenticated: false }
  post '/bookings', to: 'bookings#create', as: 'create_booking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :user
	belongs_to :camera

	validates :user_id, :camera_id, :start_date, :end_date, presence: true
	validate :valid_date_range
	validate :no_overlapping_bookings
	validate :start_date_in_future
	validate :cannot_book_own_camera

	def valid_date_range
		if start_date && end_date && start_date > end_date
		errors.add(:start_date, "must be before the end date")
		end
	end

	def no_overlapping_bookings
		overlapping_bookings = Booking.where(camera_id: camera_id)
									.where.not(id: id)
									.where("(? BETWEEN start_date AND end_date) OR (? BETWEEN start_date AND end_date) OR (start_date BETWEEN ? AND ?) OR (end_date BETWEEN ? AND ?)", start_date, end_date, start_date, end_date, start_date, end_date)

		if overlapping_bookings.exists?
			errors.add(:base, "This camera is already booked for the selected dates.")
		end
	end


	def start_date_in_future
		if start_date && start_date < Date.today
		errors.add(:start_date, "must be in the future")
		end
	end

	def cannot_book_own_camera
		if user_id == camera.user_id
			errors.add(:user_id, "cannot book own camera")
		end
	end
end

app/models/camera.rb
class Camera < ApplicationRecord
	belongs_to :user
	has_many :bookings

	validates :model, presence: true
	validates :model, length: { maximum: 100 }
	validates :price, numericality: { greater_than: 0 }
	validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cameras
  has_many :bookings

  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    # GET /bookings
    def index
      @bookings = Booking.all
    end

    # GET /bookings/:id
    def show
      @booking = Booking.find(params[:id])
    end

    # GET /bookings/new
    def new
      @camera = Camera.find(params[:camera_id])
      @booking = current_user.bookings.new(camera: @camera)
    end

    # POST /bookings
    def create
      @booking = current_user.bookings.new(booking_params)
      if @booking.save
        puts @booking.errors.full_messages
        redirect_to @booking, notice: 'Booking was successfully created.'
      else
        puts @booking.errors.full_messages
        render :new
      end
    end

    # DELETE /cameras/:id
    def destroy
      @booking = Booking.find(params[:id])
      @booking.destroy
      redirect_to cameras_url, notice: 'Camera was successfully destroyed.'
    end

    private

    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :camera_id)
    end

end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    # GET /cameras
    def index
      @cameras = Camera.all
      if user_signed_in?
        @my_cameras = current_user.cameras
      end
    end

    # GET /cameras/:id
    def show
      @camera = Camera.find(params[:id])
      if user_signed_in?
        @my_cameras = current_user.cameras
      end
    end

    # GET /cameras/new
    def new
      @camera = Camera.new
    end

    # POST /cameras
    def create

      @camera = current_user.cameras.build(camera_params)
      if @camera.save
        puts "coming here"
        redirect_to @camera, notice: 'Camera was successfully created.'
      else
        flash.now[:alert] = 'There was an error creating the camera.'
        render :new, alert: 'There was an error.'
      end
    end

    # GET /cameras/:id/edit
    def edit
      @camera = Camera.find(params[:id])
    end

    # PATCH/PUT /cameras/:id
    def update
      @camera = Camera.find(params[:id])
      if @camera.update(camera_params)
        redirect_to @camera, notice: 'Camera was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /cameras/:id
    def destroy
      @camera = current_user.cameras.find(params[:id])
      @camera.destroy
      redirect_to cameras_url, notice: 'Camera was successfully destroyed.'
    end

    private

    def camera_params
      params.require(:camera).permit(:brand, :model, :year, :price, :condition, :user_id)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = "Welcome to my Camera"
    @cameras = Camera.all
      if user_signed_in?
        @my_cameras = current_user.cameras
      end
  end

  private

  def camera_params
    params.require(:camera).permit(:brand, :model, :year, :price, :condition, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, except: [:show]

    # GET /users
    def index
      @users = User.all
    end

    # GET /users/:id
    def show
      if params[:id] == 'sign_out'
        # Handle sign out here, such as calling the sign_out method provided by Devise
        sign_out(current_user)
        redirect_to root_path, notice: 'Signed out successfully.'
      else
        @user = User.find(params[:id])
      end
    end

    # GET /users/new
    def new
      @user = User.new
    end

    # POST /users
    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to @user, notice: 'User was successfully created.'
        Rails.logger.debug("saved")
      else
        Rails.logger.debug("error")

        render :new, notice: 'There was an error'
      end
    end

    # GET /users/:id/edit
    def edit
      @user = User.find(params[:id])
    end

    # PATCH/PUT /users/:id
    def update
      if @user.update(user_params)
        redirect_back fallback_location: @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end


    # DELETE /users/:id
    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end

    private

    def user_params
      params.require(:user).permit(:name, :email, :age, :country, :password)
    end


    def set_user
      @user = User.find(params[:id]) unless params[:id] == 'sign_out'
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bookings/create.html.erb
<h1>Booking created successfully!</h1>
<p>Thank you for your booking.</p>
<%= link_to 'Back to bookings', bookings_path %>

app/views/bookings/index.html.erb
<h1>Bookings</h1>
<table>
  <thead>
    <tr>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Camera</th>
      <th>Renter</th>
      <th>Owner</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        <td><%= booking.camera.model %></td>
        <td><%= booking.camera.user.name %></td>
        <td><%= booking.user.name %></td>
        <td><%= link_to "View", booking %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Find Cameras", root_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<%= form_with(model: @booking) do |form| %>
  <%= form.hidden_field :camera_id %>

  <%= form.label :start_date, "Start Date" %>
  <%= form.text_field :start_date, id: "start_date_picker" %>

  <%= form.label :end_date, "End Date" %>
  <%= form.text_field :end_date, id: "end_date_picker" %>

  <%= form.submit "Submit" %>
<% end %>
<% if @booking.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>
<p><strong>Model:</strong> <%= @booking.camera.model %></p>
<p><strong>From:</strong> <%= @booking.start_date %></p>
<p><strong>From:</strong> <%= @booking.end_date %></p>
<p><strong>Owner:</strong> <%= @booking.camera.user.name %></p>
<p><strong>Renter:</strong> <%= @booking.user.name %></p>
<%= form_with(model: @booking, method: :delete, url: booking_path(@booking)) do |form| %>
    <%= form.submit 'Delete' %>
<% end %>
<%= link_to "More Cameras", root_path %>

app/views/cameras/index.html.erb
<h4>My Cameras</h4>

<% if user_signed_in? %>
  <table>
    <thead>
      <tr>
        <th>Model</th>
        <th>Year</th>
        <th>Condition</th>
        <th>Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @my_cameras.each do |camera| %>
        <tr>
          <td><%= camera.model %></td>
          <td><%= camera.year %></td>
          <td><%= camera.condition %></td>
          <td><%= camera.price %></td>
          <td><%= link_to "View", camera %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to "Add Camera", new_camera_path %>
<%= link_to "All Cameras", root_path %>

app/views/cameras/new.html.erb
<h1>New Camera</h1>
<%= form_with(model: @camera, url: cameras_path, local: true) do |form| %>
  <div>
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>
  <div>
    <%= form.label :year %>
    <%= form.select :year, options_for_select((1950..Date.today.year).to_a.reverse) %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price, placeholder: 'Enter price' %>
  </div>
  <div>
    <%= form.label :condition %>
    <%= form.text_field :condition %>
  </div>
  <div>
    <%= form.submit 'Add Camera' %>
  </div>
<% end %>
<p><%= link_to 'Back', cameras_path %></p>
<% if @camera.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @camera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/cameras/show.html.erb
<h1>Camera Details</h1>
<p><strong>Model:</strong> <%= @camera.model %></p>
<p><strong>Year:</strong> <%= @camera.year %></p>
<p><strong>Condition:</strong> <%= @camera.condition %></p>
<p><strong>Price:</strong> <%= @camera.price %></p>
<p><strong>Owner:</strong> <%= @camera.user.name %></p>
<% if user_signed_in? && @camera.user == current_user %>
  <p><%= link_to 'Edit', edit_camera_path(@camera) %></p>
  <%= form_with(model: @camera, method: :delete, url: camera_path(@camera)) do |form| %>
    <%= form.submit 'Delete' %>
  <% end %>
<% end %>
<% if user_signed_in? && @camera.user != current_user %>
  <%= link_to "Book this camera", new_booking_path(camera_id: @camera.id), class: "btn btn-primary" %>
<% end %>

<p><%= link_to 'Back', cameras_path %></p>

app/views/home/index.html.erb
<h1>Cameras Home</h1>
<div>
  <% if user_signed_in? %>
    <div id="react-container" data-data="<%= { message: @message, user: current_user}.to_json %>"></div>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    <%= link_to 'My Cameras', cameras_path, method: :get %>

  <% else %>
    <h4> You're not signed in </h4>
    <a href="#signin"><%= link_to 'Sign in', new_user_session_path %></a>
    <a href="#signin"><%= link_to 'Sign up', new_user_registration_path %></a>
  <% end %>
    <table>
  <% @cameras.each do |camera| %>
    <tr>
      <td><%= camera.model %></td>
      <td><%= camera.year %></td>
      <td><%= camera.condition %></td>
      <td><%= camera.price %></td>
      <td><%= link_to "View", camera %></td>
    </tr>
  <% end %>
  </table>

</div>

<%= javascript_pack_tag 'application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb2023</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'flatpickr_init' %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li><a href="#home"><%= link_to 'Home', root_path %></a></li>
    <li><a href="#mycameras"><%= link_to 'My Cameras', cameras_path %></a></li>
    <% if user_signed_in? %>
      <li>Welcome, <%= current_user.name %></li>
      <li><a href="#signout"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><a href="#signin"><%= link_to 'Sign in', new_user_session_path %></a></li>
      <li><a href="#signup"><%= link_to 'Sign up', new_user_registration_path %></a></li>
    <% end %>
  </ul>
</nav>

app/views/users/_user.html.erb
<p><strong>Name:</strong> <%= user.name %></p>
<p><strong>Email:</strong> <%= user.email %></p>

app/views/users/edit.html.erb
<h1>Edit User</h1>

  <%= form_with(model: @user, url: user_path(@user), method: :patch) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :age %>
      <%= form.number_field :age %>
    </div>

    <div>
      <%= form.label :country %>
      <%= form.text_field :country %>
    </div>

    <div>
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>

    <div>
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div>
      <%= form.submit "Update User" %>
    </div>
  <% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to "View", user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit 'Create User' %>
  </div>
<% end %>

<p><%= link_to 'Back', users_path %></p>

app/views/users/show.html.erb
<h1>User Details</h1>

<p><strong>Name:</strong> <%= @user.name %></p>
<p><strong>Age:</strong> <%= @user.age %></p>
<p><strong>Country:</strong> <%= @user.country %></p>
<p><strong>password:</strong> <%= @user.password %></p>
<p><strong>Email:</strong> <%= @user.email %></p>

<p><%= link_to 'Edit', edit_user_path(@user) %></p>
<%= link_to 'Delete', users_path, method: :delete %>

<p><%= link_to 'Back', users_path %></p>